# Generated by Django 4.1.2 on 2022-12-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='password',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='username',
            new_name='speciality',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
